-- Run this in Supabase SQL Editor.
-- The Node.js backend uses the Supabase server-side key, so it can securely
-- access these tables and the private Storage bucket.

CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(12),
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    subject VARCHAR(255) NOT NULL,
    assignment_details TEXT NOT NULL,
    deadline_date DATE NOT NULL,
    deadline_time TIME NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'New',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT submissions_status_check
      CHECK (status IN ('New','In Progress','Completed','Cancelled'))
);

CREATE TABLE IF NOT EXISTS public.submission_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
    original_file_name VARCHAR(500) NOT NULL,
    stored_file_name VARCHAR(500) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    mime_type VARCHAR(255),
    file_size BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migration support for databases created with an older schema.
ALTER TABLE public.submissions
  ADD COLUMN IF NOT EXISTS order_id VARCHAR(12);

CREATE INDEX IF NOT EXISTS idx_submissions_order_id ON public.submissions(order_id);

CREATE INDEX IF NOT EXISTS idx_submissions_email ON public.submissions(email);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON public.submissions(status);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON public.submissions(created_at);
CREATE INDEX IF NOT EXISTS idx_submission_attachments_submission_id ON public.submission_attachments(submission_id);

-- Backend-only access. The Node.js server uses the Supabase service-role key.
-- Keep these tables protected from direct anonymous browser access.
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Create the private Storage bucket if it does not already exist.
INSERT INTO storage.buckets (id, name, public)
VALUES ('assignment-files', 'assignment-files', false)
ON CONFLICT (id) DO NOTHING;

-- Neon PostgreSQL file storage (no Supabase services required)
CREATE TABLE IF NOT EXISTS submission_files (id BIGSERIAL PRIMARY KEY, submission_id BIGINT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, original_file_name VARCHAR(500) NOT NULL, stored_file_name VARCHAR(500) NOT NULL, file_path VARCHAR(1000) NOT NULL, mime_type VARCHAR(255), file_size BIGINT, data BYTEA NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
